export const GET_EMAIL = "GET_EMAIL";
export const SUBSCRIBE_FOR_NEWSLETTERS_REQUESTING = "SUBSCRIBE_FOR_NEWSLETTERS_REQUESTING"
export const SUBSCRIBE_FOR_NEWSLETTERS_SUCCESS = "SUBSCRIBE_FOR_NEWSLETTERS_SUCCESS"
export const SUBSCRIBE_FOR_NEWSLETTERS_ERROR = "SUBSCRIBE_FOR_NEWSLETTERS_ERROR"
export const CLOSE_MODAL_WINDOW ="CLOSE_MODAL_WINDOW";

